### ISSUE TITLE
Sample project not working

### ISSUE THREAD

**Issue by infinitey** [ttdat89/react-native-video-quickblox#4]
So sorry to keep bringing up issues. Although I had managed to get the app running on both iOS and Android phones, I am unable to establish calls. 

I login on iOS app as dat.tran and  phuc.tran for Android app.  Android app will always crash right away upon calling from iOS app. Unable to get any error messages unfortunately due to sudden crash.

When I tried calling from Android to iOS app, nothing will happen. Both apps will just get locked in Camera screen without being able to hang up calls (hang up button not working?).

**Comment by ttdatt** [comment]
I just publish new version 1.0.16 to npm. Can you try again?

**Comment by ttdatt** [comment]
Just check again, there is something wrong with new Quickblox version

**Comment by infinitey** [comment]
Yup, I just updated to 1.0.16.

When iOS phone calling Android, there is no more crashes but video images are blank on both sides.
When Android phone is calling iOS, there is no response on the iOS app at all.

**Comment by ttdatt** [comment]
Hi @infinitey , can you download the sample project and run again. I just fix Quickblox version on both iOS and Android. It works.

I will fix bug with new Quickblox later.

**Comment by infinitey** [comment]
Sure trying now!

**Comment by infinitey** [comment]
Hey, tried a few times but the same issues still remains.
When iOS phone calling Android, there is no more crashes but video images are blank on both sides.
When Android phone is calling iOS, there is no response on the iOS app at all.

When I download your project, I had to make this changes in order for the android app to run:

android/app/build.gradle
```
   defaultConfig {
        ...
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    } 
```

android/build.gradle
```
buildscript {
    repositories {
        ...
        maven { url 'https://maven.google.com' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0'
    }
}

allprojects {
    repositories {
		...
                maven { url 'https://maven.google.com' }
    }
}
```

android/gradle.properties
```
android.useDeprecatedNdk=true
org.gradle.jvmargs=-Xmx1536M
```

\node_modules\react-native-spinkit\android\build.gradle
```
android {
    compileSdkVersion 25
    buildToolsVersion "25.0.0"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
    }
```

\android\gradle\wrapper\gradle-wrapper.properties
`distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip`



For iOS side:
When I use 'pod install' normally, it gives this error:
```
None of your spec sources contain a spec satisfying the dependencies: `Quickblox-WebRTC (~> 2.6.1), Quickblox-WebRTC (= 2.6.1)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```
I had to use 'pod install --repo-update' in order for the iOS app to run.

Hope this helps you to find the issue.

**Comment by ttdatt** [comment]
Forgot commit build.gradle in the library. It works now

**Comment by infinitey** [comment]
Hey, it's working now. Thanks for your help.

I will be working on a project using your package. Might contribute to your package if you do not mind.

**Comment by ttdatt** [comment]
You're welcome.
